config/routes.rb
Rails.application.routes.draw do
  resources :helpers
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/helper.rb
class Helper < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def home
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: %i[ show edit update destroy ]

  # GET /helpers or /helpers.json
  def index
    @helpers = Helper.all
    @helpers = policy_scope(Helper)
  end

  # GET /helpers/1 or /helpers/1.json
  def show
    authorize @helper
  end

  # GET /helpers/new
  def new
    @helper = Helper.new
    authorize @helper
  end

  # GET /helpers/1/edit
  def edit
    authorize @helper
  end

  # POST /helpers or /helpers.json
  def create
    @helper = Helper.new(helper_params)
    @helper.user_id = current_user.id
    authorize @helper
    respond_to do |format|
      if @helper.save
        format.html { redirect_to helper_url(@helper), notice: "Helper was successfully created." }
        format.json { render :show, status: :created, location: @helper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helpers/1 or /helpers/1.json
  def update
    authorize @helper
    respond_to do |format|
      if @helper.update(helper_params)
        format.html { redirect_to helper_url(@helper), notice: "Helper was successfully updated." }
        format.json { render :show, status: :ok, location: @helper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helpers/1 or /helpers/1.json
  def destroy
    authorize @helper
    @helper.destroy

    respond_to do |format|
      format.html { redirect_to helpers_url, notice: "Helper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helper
      @helper = Helper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def helper_params
      params.require(:helper).permit(:occupation, :summary)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/helpers/_form.html.erb
<%= simple_form_for(@helper) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :occupation %>
    <%= f.input :summary %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/helpers/_helper.html.erb
<div id="<%= dom_id helper %>">
  <p>
    <strong>Occupation:</strong>
    <%= helper.occupation %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= helper.summary %>
  </p>

  <p>
    <strong>User:</strong>
    <%= helper.user_id %>
  </p>

</div>

app/views/helpers/edit.html.erb
<h1>Editing helper</h1>

<%= render "form", helper: @helper %>

<br>

<div>
  <%= link_to "Show this helper", @helper %> |
  <%= link_to "Back to helpers", helpers_path %>
</div>

app/views/helpers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Helpers</h1>

<div id="helpers">
  <% @helpers.each do |helper| %>
    <%= render helper %>
    <p>
      <%= link_to "Show this helper", helper %>
    </p>
  <% end %>
</div>

<%= link_to "New helper", new_helper_path if policy(Helper).new? %>

app/views/helpers/new.html.erb
<h1>New helper</h1>

<%= render "form", helper: @helper %>

<br>

<div>
  <%= link_to "Back to helpers", helpers_path %>
</div>

app/views/helpers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @helper %>

<div>
  <% if policy(@helper).edit? %>
    <%= link_to "Edit this helper", edit_helper_path(@helper) %> |
  <% end %>
  <%= link_to "Back to helpers", helpers_path %>

  <%= button_to "Destroy this helper", @helper, method: :delete if policy(@helper).destroy? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeBetter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "new helper account", new_helper_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>